export default {
  newWallet: {
    createWallet: "Create New Wallet",
    enterPass1: "Enter your wallet password",
    enterPass2: "Confirm your wallet password",
    saveKeyStore: "Save Your Keystore File",
    keyStoreDown: "Keystore Download",
    next: "Next",
    savePrivateKey: "Save your Private Key"
  },
  tipsListPass: {
    "tipsCnt1": "Please ensure it is a strong password.",
    "tipsCnt2": "Password should not start or end with space.",
    "tipsCnt3": "The download file contains your wallet info, don't share it to others, otherwise your money will be stolen."
  },
  tipsListKey: {
    "tipsCnt1": "Do not lose it! It cannot be recovered if you lose it.",
    "tipsCnt2": "Do not share it! Your funds may be stolen if you use this file on a malicious/phishing site.",
    "tipsCnt3": "Make a backup! Secure it like the millions of dollars it may one day be worth."
  },
  passTips: {
    passFormat:"8-30 characters, must contain at least 2 types of numbers, English letters, and special characters.",
    passNoMatch: "Password doesn't match , please try again.",
    passFormatError: "The password format is incorrect, please reenter it.",
    passEncryption: "Your wallet is encrypted! Please enter the password",
    newWalletPass: "Enter your new wallet password",
    passError: "Password error, unlock fail.",
  },
  walletInfo: {
    accessWallet: "How would you like to access your wallet?",
    privateKey: "Private Key",
    invalidPrivateKey: "This is not a valid private key.",
    checkKeyStore1: "Select Your Keystore",
    checkKeyStore2: "Select Keystore",
    unlock: "Unlock",
    inputPrivateKey1: "Enter Your Private Key",
    inputPrivateKey2: "Enter your wallet Private Key",
    walletAddress: "Address",
    walletPrivateKey: "Private Key",
    walletMoney: "Balance",
    qrCode: "Your address (QR Code)",
    newKeyStore: "Download New Keystore",
  },
  transfer: {
    youAddress: "From address",
    transferAdddress: "To",
    transferNumber: "Amount",
    balance: "Balance",
    all: "All",
    generateTrading: "Generate transaction",
    confirmTransferInfo: "Confirm the following information",
    orderInfo: "Order information",
    transferTxt: "Transfer",
    collectionAddress: "Receive",
    paymentAddress: "Sent",
    transferAomunt: "Amount",
    transferMoneyError: "Please enter the correct transfer amount.",
    transferMoney: "Amount is not valid.",
    transferMoney1: "The transfer amount must not be 0",
    transferMoneyN: "Transfer fee must be less than balance.",
    transferMoneyN1: "Poundage cannot be 0.",
    transferAddressError: "This is not a valid address.",
    transferAddressError2: "The same address cannot be transferred.",
    transferError: 'Transfer failed, please try again later.',
    transferPoundage: 'Fee',
    transferPoundage1: 'Gas Price',
    transferFast: 'Fast',
    transferSlow: 'Slow',
  },
  mapping: {
    ethaddress: 'ETH Wallet Address',
    ethwalletddress: 'ETH Wallet Address',
    mappingTipsTxt1: 'Please try to map the same ETH address completely, one transfer, corresponding to submit a mapping request; if you transfer multiple transactions, you need to submit multiple mapping requests.',
    mappingTipsTxt2: "Please use ETH's private key to log in and view BIUT wallet.",
    mappingTipsTxt3: 'If in doubt, check out the help mapping tutorial.',
    ethAddressErrorTxt: 'ETH address error',
    tipTxt: 'Notice',
    confirmMapping: 'Confirm the following information',
    mappingButton: 'Mapping',
    mappingButtonAcitve: 'Mapping...',
    mappingSuccess: 'Submit the mapping successfully. Please wait for 1-3 working days to check BIUT arrival in the new wallet address.  If you have any questions, please contact the BIUT staff.',
    mappingFailure1: 'Eth Transaction Hash Error or Eth Address Error or Your transaction not confirmed in Eth network, please try again later...',
    mappingFailure2: 'You have already submitted!',
    mappingFailure3: 'System Error, please try again later!',
    mappingHash: 'ETH Transaction Hash',
    mappingHashError: 'Invalid transaction hash',
    mappingHashTxt: 'Please enter the transaction hash value transferred on ETH',
  },
  pool: {
    poolBanner: 'BIUT矿池正式上线啦',
    poolLogin: '欢迎登入',
    poolLoginIpt: '请输入钱包私钥',
    poolLoginIptError: '请输入正确的钱包私钥',
    poolLoginBtn: '登入',

    poolIndexL: '未登入',
    poolIndexE: '退出',
    poolIndexListTit1: '矿池名称',
    poolIndexListTit2: '日产值',
    poolIndexListTxt1: '已加入',
    poolIndexListTxt2: '加入',
    poolIndexIpt: '搜索',
    poolIndexTit1: '矿池',
    poolIndexTitLook: '查看所有矿池',
    poolIndexTit2: '加入矿池',
    poolIndexTit3: '收益记录',

    poolIndexTxt1: '过去24小时收益',
    poolIndexTxt2: '总收益',
    poolIndexTxt3: '加入矿池冻结资产',
    poolIndexTxt4: '账户可用余额',

    poolIndexSearch1: '共找到',
    poolIndexSearch2: '条 关于',
    poolIndexSearch3: '的矿池结果',
  },
  pages: {
    next: '下一页',
    prev: '上一页',
  },
  mask: {
    tips: "Operation success, click the URL below to view the results：",
    confirm: "Confirm",
    confirms: "Confirm...",
    cancel: "Cancal",

    poolTips: '提示',
    poolBtn: '我知道了',
    poolTxt: '你已加入矿池哦，无法再加入其它矿池！',
    pooTit: '加入矿池',
    poolNumber: '抵押数量',
    poolNumberError: '加入矿池最低数量为1000 BIUT',
    poolTxt1: '抵押数量会被冻结一年，抵押数量越多，挖到BIU的收益越高哦！',
    poolBtn1: '确认加入'
  },
  headerNav: {
    "Newallet": "New Wallet",
    "ViewWalletInfo": "Wallet Info",
    "TransferSEC": "Transfer",
    "Guide": "Guide",
    "Language": "Language",
    "Mapping": "Mapping",
    "orePool": '矿池'
  },
  helpTips: {
    helpTipsTxt: 'Check out the tutorial on your computer.'
  },
  footer: {
    FooterCnt: "Any question? Please contact us.Official email address"
  }
}