export default {
  newWallet: {
    createWallet: "Create New Wallet",
    enterPass1: "Enter your wallet password",
    enterPass2: "Confirm your wallet password",
    saveKeyStore: "Save Your Keystore File",
    keyStoreDown: "Keystore Download",
    createBtn: 'Create New Wallet',
    createBtns: 'Create New Wallet ...',
    next: "Next",
    savePrivateKey: "Save your Private Key",

    codeIpt: "Please enter the invitation code",
    codeIptError: "Please enter the correct invitation code",
  },
  tipsListPass: {
    "tipsCnt1": "Please ensure it is a strong password.",
    "tipsCnt2": "Password should not start or end with space.",
    "tipsCnt3": "The download file contains your wallet info, don't share it to others, otherwise your money will be stolen."
  },
  tipsListKey: {
    "tipsCnt1": "Do not lose it! It cannot be recovered if you lose it.",
    "tipsCnt2": "Do not share it! Your funds may be stolen if you use this file on a malicious/phishing site.",
    "tipsCnt3": "Make a backup! Secure it like the millions of dollars it may one day be worth."
  },
  passTips: {
    passFormat:"8-30 characters, must contain at least 2 types of numbers, English letters, and special characters.",
    passNoMatch: "Password doesn't match , please try again.",
    passFormatError: "The password format is incorrect, please reenter it.",
    passEncryption: "Your wallet is encrypted! Please enter the password",
    newWalletPass: "Enter your new wallet password",
    passError: "Password error, unlock fail.",
    inviteCodeError: "Invalid input."
  },
  walletInfo: {
    accessWallet: "How would you like to access your wallet?",
    privateKey: "Private Key",
    invalidPrivateKey: "This is not a valid private key.",
    checkKeyStore1: "Select Your Keystore",
    checkKeyStore2: "Select Keystore",
    unlock: "Unlock",
    unlockBtn: 'Unlock',
    unlockBtns: 'Unlock...',

    inputPrivateKey1: "Enter Your Private Key",
    inputPrivateKey2: "Enter your wallet Private Key",
    walletAddress: "Address",
    walletPrivateKey: "Private Key",
    walletMoney: "Balance",
    qrCode: "Your address (QR Code)",
    newKeyStore: "Download New Keystore",

    myCodeTxt: 'My invitation code',
    shareBtn: 'Share',
  },
  transfer: {
    youAddress: "From address",
    transferAdddress: "To",
    transferNumber: "Amount",
    balance: "Available",
    all: "All",
    generateTrading: "Generate transaction",
    confirmTransferInfo: "Confirm the following information",
    orderInfo: "Order information",
    transferTxt: "Transfer",
    collectionAddress: "Receive",
    paymentAddress: "Sent",
    transferAomunt: "Amount",
    transferMoneyError: "Please enter the correct transfer amount.",
    transferMoney: "Amount is not valid.",
    transferMoney1: "The transfer amount must not be 0",
    transferMoneyN: "Transfer fee must be less than balance.",
    transferMoneyN1: "Poundage cannot be 0.",
    transferAddressError: "This is not a valid address.",
    transferAddressError2: "The same address cannot be transferred.",
    transferError: 'Transfer failed, please try again later.',
    transferPoundage: 'Fee',
    transferPoundage1: 'Gas Price',
    transferFast: 'Fast',
    transferSlow: 'Slow',
  },
  mapping: {
    ethaddress: 'ETH Wallet Address',
    ethwalletddress: 'ETH Wallet Address',
    mappingTipsTxt1: 'Please try to map the same ETH address completely, one transfer, corresponding to submit a mapping request; if you transfer multiple transactions, you need to submit multiple mapping requests.',
    mappingTipsTxt2: "Please use ETH's private key to log in and view BIUT wallet.",
    mappingTipsTxt3: 'If in doubt, check out the help mapping tutorial.',
    ethAddressErrorTxt: 'ETH address error',
    tipTxt: 'Notice',
    confirmMapping: 'Confirm the following information',
    mappingButton: 'Mapping',
    mappingButtonAcitve: 'Mapping...',
    mappingSuccess: 'Submit the mapping successfully. Please wait for 1-3 working days to check BIUT arrival in the new wallet address.  If you have any questions, please contact the BIUT staff.',
    mappingFailure1: 'Eth Transaction Hash Error or Eth Address Error or Your transaction not confirmed in Eth network, please try again later...',
    mappingFailure2: 'You have already submitted!',
    mappingFailure3: 'System Error, please try again later!',
    mappingHash: 'ETH Transaction Hash',
    mappingHashError: 'Invalid transaction hash',
    mappingHashTxt: 'Please enter the transaction hash value transferred on ETH',
  },
  pool: {
    poolBanner: 'The BIUT mine pool is officially online',
    poolLogin: 'Enter Wallet',
    poolLoginIpt: 'Eenter your private key here',
    poolLoginIptError: 'Please enter the correct wallet private key.',
    poolInvailidError: 'Invailid wallet address',
    poolLoginBtn: 'Enter Wallet',
    poolLoginBtns: 'Enter Wallet...',

    poolIndexL: 'Login',
    poolIndexE: 'Log out',
    poolIndexListTit1: 'Name',
    poolIndexListTit2: 'Nissan',
    poolIndexListTxt1: 'Joined',
    poolIndexListTxt2: 'Join',
    poolIndexIpt: 'Search',
    poolIndexTit1: 'Mine Pool',
    poolIndexTitLook: 'View All Mine Pools',
    poolIndexTit2: 'Join The Mine Pool',
    poolIndexTit3: 'Profit Record',

    poolIndexTxt1: "Last week's earnings",
    poolIndexTxt2: 'Total Profit',
    poolIndexTxt3: 'Frozen Assets In Mine Pool',
    poolIndexTxt4: 'Available Balance',

    poolIndexSearch1: 'Found',
    poolIndexSearch2: 'results for',
    poolIndexSearch3: '',

    poolTabTxt1: 'Mining pool',
    poolTabTxt2: 'The invitation',
    poolListNull: 'No record',
  },
  invitation: {
    level: 'My Level',
    medal: 'Gold medal',
    rules: 'View rules',

    inListTit: 'Invitation record',
    inListSearch: 'Enter address to search',
    inListTxt1: 'Address',
    inListTxt2: 'Invitation time',
    inListTxt3: 'Total reward (BIUT)',
    inListTxt4: 'View details',
    inListNull: 'Uninvited record',
    inListSearchNull: 'No search results yet',

    inMaskTxt: 'Every time the invitation is successful, it will reward BIUT, please check it.',
    inMaskListTxt1: 'Level',
    inMaskListTxt2: 'Number of people',

    inMask2ListTxt1: 'Time',
    inMask2ListTxt2: 'Reward (BUT)',

    level1: 'Bronze partner',
    level2: 'Silver partner',
    level3: 'Gold partner',
    level4: 'Super partner',
    level4Txt: 'More than 64',

    invitationTipsTxt1: 'Lock the bin BIUT on the mining page and unlock the invitation code!',
    invitationTipsTxt2: "In the mining page to lock 10,000 BIUT or join the mining pool, you can share a key!"
  },
  mask: {
    tips: "Operation success, click the URL below to view the results：",
    confirm: "Confirm",
    confirms: "Confirm...",
    cancel: "Cancal",

    poolTips: 'Information',
    poolBtn: 'I know it',
    poolTxt: 'You have joined the mine pool and can not join others.',
    poolNumber: 'locked amount',
    poolNumberError: 'At least 10,000 BIUT is required to join the mine pool.',
    poolTxt1: 'locked BIUT will be frozen one year. The more BIUT locked, the more profits of mining BIU',
    poolBtn1: 'Join Now'
  },
  headerNav: {
    "Newallet": "New Wallet",
    "ViewWalletInfo": "Wallet Info",
    "TransferSEC": "Transfer",
    "Guide": "Guide",
    "Language": "Language",
    "Mapping": "Mapping",
    "orePool": 'Mine Pool'
  },
  helpTips: {
    helpTipsTxt: 'Check out the tutorial on your computer.'
  },
  footer: {
    FooterCnt: "Any question? Please contact us.Official email address"
  },
  public: {
    available: 'Available',
    guarantee: 'Guarantee',
    pageNext: 'Next',
    pagePrev: 'Prev',

    pageTotal: '',
    pageRecord: ' records',
    pageResults: ' of results',

    systemError: 'System exception',
  },
  share: {
    shareTit1: 'BIUT- PC Mining POW',
    shareTit2: 'Mining invitation code',
    shareTxt1: 'Use the browser scan to view',
    shareTxt2: 'Save picture',
  }
}